### ISSUE TITLE
Tutorial feedback - Creating widgets

### ISSUE THREAD

**Issue by umaar** [dojo/dojo.io#230] opened 2017-10-19 15:07 UTC
Link: https://dojo.io/tutorials/003_creating_widgets/#7

> The application now renders three workers in the WorkerContainer widget, allowing us to control how they are laid out without impacting the overall application.

Would be nice to see a screenshot of what the app should look like at this point.

**Comment by kitsonk** [comment] 2017-10-20 09:24
Duplicate of #266

Let's keep this one comment as a single concept/idea.

**Closed by kitsonk** 2017-10-20 09:24 UTC
