### ISSUE TITLE
Navigating quickly using browser buttons breaks the tutorial router

### ISSUE THREAD

**Issue by edhager** [dojo/dojo.io#299] opened 2017-10-26 18:36 UTC
Steps to reproduce:

1. Go to a tutorial: https://dojo.io/tutorials/001_static_content/#1
1. Use the "Next" button to navigate to the last page of the tutorial.
1. Use the browser's back button to return to the first page of the tutorial.
1. Quickly click the browser's forward button to go to the last page of the tutorial.

The last page will be blank.

![tutorial-naviagate-bug](https://user-images.githubusercontent.com/4441986/32070643-e4a5595a-ba41-11e7-981b-be1504c652a8.gif)

**Comment by dylans** [comment] 2017-10-27 16:13
@edhager, I think this is a duplicate of #181?

**Comment by kitsonk** [comment] 2017-10-30 08:59
It is at least related.

**Comment by edhager** [comment] 2017-10-31 16:49
It is probably related.  I was thinking #181 had been fixed.  When I was testing #181, I didn't try the browser buttons.  So I guess this one's good just in case there are any differences.

**Closed** 2018-01-08 16:28 UTC
Labels: Infrastructure, blocker, bug
