### ISSUE TITLE
Tutorial uses inline styles

### ISSUE THREAD

**Issue by smhigley** [dojo/dojo.io#75] opened 2017-04-17 19:22 UTC
Since inline styles are considered an anti-pattern, should we remove them from the tutorials?

Used in `widgets/Banner.ts` here:
https://github.com/dojo/dojo.io/blob/master/site/source/tutorials/003_creating_widgets/demo/initial/biz-e-corp/src/widgets/Banner.ts#L8

**Comment by dylans** [comment] 2017-04-18 12:27
My suggestion is yes... cc @rishson

**Comment by rishson** [comment] 2017-04-18 12:31
Yup - that needs to change to use `title` rather than `styles`.

**Comment by vansimke** [comment] 2017-04-24 13:06
I think this is a dupe of #51.

**Comment by vansimke** [comment] 2017-04-25 13:54
Closed via #86

**Closed by vansimke** 2017-04-25 13:54 UTC
